version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.2

jobs:
  deploy:
    working_directory: ~/repo
    docker:
      - image: google/cloud-sdk:latest

    steps:
      - run:
          name: start to deploy
          command: |
            curl https://challenge-every-month-404e2.appspot.com/slack/deploying
      - checkout
      - run:
          name: Overwrite env variables
          command: |
            echo "env_variables:" >> app.yaml
            echo "  SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}" >> app.yaml
            echo "  SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}" >> app.yaml
      - gcp-cli/initialize
      - run:
          name: build
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | bash -
            apt-get install -y nodejs
            npm i
            npm run build
      - run:
          name: Deploy to Google App Engine
          command: |
            gcloud app --quiet deploy app.yaml
      - run:
          name: deployed successfully
          command: |
            curl https://challenge-every-month-404e2.appspot.com/slack/deployed
  lint:
    docker:
      - image: circleci/node:10
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: lint
          command: |
            mkdir -p /tmp/test-reports/eslint
            yarn lint --quiet --format junit --output-file /tmp/test-reports/eslint/results.xml
      - store_test_results:
          path: /tmp/test-reports

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
      - lint:
          filters:
            branches:
              only:
                - /^(?!master$).+$/
